[tools]
dotnet = "9"
gh = "latest"

[tasks."setup:mise"]
description = "Install the pinned tools via mise"
run = "mise install"
alias = "sm"
sources = ["mise.toml"]
outputs = { auto = true }
wait_for = ["nuke"]

[tasks."setup:dotnet"]
description = "Restore .NET dependencies"
run = [
  "dotnet tool restore", # restore any dotnet tools
  "dotnet restore",      # restore all nuget dependencies
]
alias = "sd"
wait_for = ["nuke", "clean"]

[tasks.setup]
description = "Setup the environment"
depends = ["setup:mise", "setup:dotnet", "setup:binaryen-shared"]
wait_for = ["nuke", "clean"]
alias = "s"

[tasks.build]
description = "Build .NET managed code"
run = "dotnet build --no-restore -p:GeneratePackageOnBuild=false"
alias = "b"
depends = ["setup"]

[tasks.test]
description = "Run tests for current runtime or pass -r <RID>"
run = "dotnet test --no-build --configuration Release --verbosity minimal --logger \"trx;LogFilePrefix=test-results\""
alias = "t"
depends = ["build --configuration Release"]

[tasks.clean]
description = "Run dotnet clean on all projects"
run = "dotnet clean"
alias = "c"

[tasks.nuke]
description = "Delete all artifacts"
run = ["rm -rf artifacts"]
alias = "n"

[tasks.pack]
description = "Create NuGet packages into artifacts/package"
depends = ["setup", "build --configuration Release"]
run = "dotnet pack --no-restore --no-build -c Release --output artifacts/package"
alias = "p"

[tasks.rebuild]
description = "Clean and build the solution"
depends = ["clean", "build --configuration Release"]
alias = "r"

[tasks.fresh]
description = "Nuke, build and test"
depends = ["nuke", "test"]
alias = "fr"
